version: "3.7"

services:
    app:
        build:
            context: .
        ports:
            - '8000:8000'
        volumes:
            - ./backend:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                    python manage.py runserver 0.0.0.0:8000"
        env_file: .env
        depends_on:
            - db
        tty: true

    db:
        image: postgres:10-alpine
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        env_file: .env.db
