// Auth actions

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_USER_SIGNUP = 'AUTH_USER_SIGNUP';
export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';
export const AUTH_USER_ACTIVATION = 'AUTH_USER_ACTIVATION';
export const AUTH_USER_ACTIVATION_SUCCESS = 'AUTH_USER_ACTIVATION_SUCCESS';
export const AUTH_USER_ACTIVATION_FAIL = 'AUTH_USER_ACTIVATION_FAIL';
export const AUTH_USER_LOADED_SUCCESS = 'AUTH_USER_LOADED_SUCCESS';
export const AUTH_USER_LOADED_FAIL = 'AUTH_USER_LOADED_FAIL';
export const AUTH_LOAD_USER = 'AUTH_LOAD_USER';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REMEMBER_ME = 'AUTH_REMEMBER_ME';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET';
export const AUTH_PASSWORD_RESET_FAIL = 'AUTH_PASSWORD_RESET_FAIL';
export const AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS';
export const AUTH_PASSWORD_RESET_CONFIRM = 'AUTH_PASSWORD_RESET_CONFIRM';
export const AUTH_PASSWORD_RESET_CONFIRM_FAIL = 'AUTH_PASSWORD_RESET_CONFIRM_FAIL';
export const AUTH_PASSWORD_RESET_CONFIRM_SUCCESS = 'AUTH_PASSWORD_RESET_CONFIRM_SUCCESS';

// Snackbar actions

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';