# Generated by Django 3.1.11 on 2021-06-09 21:39

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255, verbose_name='nombre de la empresa')),
                ('business_type', models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Consultorio', 'Consultorio'), ('Hospital', 'Hospital'), ('Clínica', 'Clínica'), ('Distribuidora', 'Distribuidora'), ('Gubernamental', 'Gubernamental')], max_length=255)),
                ('rif', models.ImageField(null=True, upload_to=core.models.user_rif_image_file_path)),
                ('rif_address', models.CharField(blank=True, max_length=255)),
                ('rif_validated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('roles', models.CharField(choices=[('user', 'Usuario'), ('staff', 'Empleado'), ('admin', 'Administrador')], default='user', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='CharacteristicTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_image', models.ImageField(null=True, upload_to=core.models.product_image_file_path)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('test', 'Test')], default='publicado', max_length=10)),
                ('brand', models.ManyToManyField(to='core.Brand', verbose_name='Marca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rif', models.CharField(max_length=20)),
                ('rif_image', models.ImageField(null=True, upload_to=core.models.supplier_rif_file_path)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Precio del Producto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product', verbose_name='ID Producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.supplier', verbose_name='ID Proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_Main', models.BooleanField(verbose_name='Flag de Correo Pricipal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_payment_date', models.DateTimeField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.bank', verbose_name='Banco')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.currency', verbose_name='Moneda')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymentmethod', verbose_name='Método de Pago')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymentstatus', verbose_name='Estado del Pago')),
                ('purchase_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.purchasestatus', verbose_name='Estado de la Compra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('characteristic_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.characteristictypes', verbose_name='Tipo de Característica')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.product', verbose_name='ID Tipo de Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillProductCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_detail', models.ManyToManyField(to='core.BillDetail')),
                ('characteristic_sel', models.ManyToManyField(to='core.CharacteristicTypes')),
            ],
        ),
        migrations.CreateModel(
            name='BillPaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt_number', models.FloatField()),
                ('payment_receipt_image', models.ImageField(upload_to=core.models.bill_payment_receipt_image_file_path)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.purchasebill', verbose_name='Factura de la Compra')),
            ],
        ),
        migrations.AddField(
            model_name='billdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.supplierproducts'),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='purchase_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.purchasebill', verbose_name='Factura de la Compra'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(to='core.Specialization', verbose_name='listado de especializaciones'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
