# Generated by Django 3.1.8 on 2021-04-26 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255, verbose_name='nombre de la empresa')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_Main', models.BooleanField(verbose_name='Flag de Correo Pricipal')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'paquete'), ('C', 'caja'), ('B', 'bulto'), ('U', 'unitario')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rif', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_Main', models.BooleanField(verbose_name='Flag de Correo Pricipal')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('description', models.CharField(max_length=255)),
                ('is_Main', models.BooleanField(verbose_name='Flag de Telefono Pricipal del Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rif', models.CharField(max_length=20)),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('bank_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.bank', verbose_name='ID Banco')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_accounts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.supplierbankaccounts'),
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_date', models.DateTimeField()),
                ('purchase_payment_date', models.DateTimeField()),
                ('bank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.bank', verbose_name='Banco')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.currency', verbose_name='Moneda')),
                ('payment_method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.paymentmethod', verbose_name='Método de Pago')),
                ('payment_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.paymentstatus', verbose_name='Estado del Pago')),
                ('purchase_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.purchasestatus', verbose_name='Estado de la Compra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_family', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.productfamily', verbose_name='ID Familia de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.brand', verbose_name='Marca')),
                ('presentation_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.presentationtype', verbose_name='ID Presentacion')),
                ('product_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.producttype', verbose_name='ID Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('is_Main', models.BooleanField(verbose_name='Flag de Telefono Principal')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.deparment', verbose_name='ID Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('bank_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.bank', verbose_name='ID Banco')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.ManyToManyField(to='core.BusinessType'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='SupplierProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Precio del Producto')),
                ('stock', models.FloatField(verbose_name='Cantidad de Productos en Existencia')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='ID Producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='ID Proveedor')),
            ],
            options={
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
