# Generated by Django 3.1.11 on 2021-06-14 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='rif_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='currency',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasestatus',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproducts',
            name='stock',
            field=models.FloatField(default=1, verbose_name='Inventario del Producto del Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
