# Generated by Django 3.1.8 on 2021-04-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('P', 'paquete'), ('C', 'caja'), ('B', 'bulto'), ('U', 'unitario')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='businesstype',
            old_name='nombre',
            new_name='name',
        ),
    ]
