# Generated by Django 3.1.11 on 2021-06-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210614_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieremails',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='ID Distribuidor'),
            preserve_default=False,
        ),
    ]
