# Generated by Django 3.1.8 on 2021-04-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210426_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialitation',
            new_name='Specialization',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(to='core.Specialization'),
        ),
    ]
