# Generated by Django 3.1.8 on 2021-04-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210426_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('Pe', 'Personal'), ('Co', 'Consultorio'), ('Ho', 'Hospital'), (
                'Cl', 'Clínica'), ('Di', 'Distribuidora')], default='Personal', max_length=255),
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('Al', 'Alergología'), ('An', 'Anestesiología'), ('Ca', 'Cardiología'), (
                'En', 'Endocrinología'), ('Ga', 'Gastroenterología'), ('Me', 'Medicina')], default='Medicina', max_length=255),
        ),
        migrations.DeleteModel(
            name='BusinessType',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
