# Generated by Django 3.1.11 on 2021-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supplieremails_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproductcharacteristics',
            name='characteristic_sel',
            field=models.ManyToManyField(to='core.ProductCharacteristics'),
        ),
    ]
