# Generated by Django 3.1.11 on 2021-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210615_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_payment_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
