# Generated by Django 3.1.11 on 2021-06-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210615_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='bank',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='payment_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymentmethod', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
