# Generated by Django 3.1.8 on 2021-04-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210426_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Consultorio', 'Consultorio'), ('Hospital', 'Hospital'), ('Clínica', 'Clínica'), ('Distribuidora', 'Distribuidora')], default='Personal', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('Alergología', 'Alergología'), ('Anestesiología', 'Anestesiología'), ('Cardiología', 'Cardiología'), ('Endocrinología', 'Endocrinología'), ('Gastroenterología', 'Gastroenterología'), ('Medicina', 'Medicina')], default='Medicina', max_length=255),
        ),
    ]
