# Generated by Django 3.1.11 on 2021-06-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210615_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproductcharacteristics',
            name='bill_detail',
        ),
        migrations.AddField(
            model_name='billproductcharacteristics',
            name='bill_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.billdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.currency', verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymentmethod', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
