# Generated by Django 3.1.11 on 2021-06-26 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210622_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
    ]
