# Generated by Django 3.1.8 on 2021-04-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210427_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationtype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
    ]
