# Generated by Django 3.1.8 on 2021-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_presentationtype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='presentation_type',
            field=models.CharField(choices=[('P', 'paquete'), ('C', 'caja'), ('B', 'bulto'), ('U', 'unitario')], default='paquete', max_length=255),
        ),
        migrations.DeleteModel(
            name='PresentationType',
        ),
    ]
