# Generated by Django 3.1.11 on 2021-06-26 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_billdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpaymentdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billproductcharacteristics',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
            preserve_default=False,
        ),
    ]
