# Generated by Django 3.1.11 on 2021-06-27 22:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210626_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpaymentdetail',
            name='payment_receipt_image',
            field=models.ImageField(null=True, upload_to=core.models.bill_payment_receipt_image_file_path),
        ),
        migrations.AlterField(
            model_name='billpaymentdetail',
            name='payment_receipt_number',
            field=models.BigIntegerField(),
        ),
    ]
