# Generated by Django 3.1.11 on 2021-08-06 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210627_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedmovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='likedmovie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='LikedMovie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
