# Generated by Django 3.1.9 on 2021-05-23 23:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210504_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to=core.models.product_image_file_path),
        ),
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rif',
            field=models.ImageField(null=True, upload_to=core.models.user_rif_image_file_path),
        ),
    ]
