# Generated by Django 3.1.11 on 2021-08-07 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_billclientsubmission_deliverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='bill_client_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.billclientsubmission', verbose_name='Solicitud del Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='delivery_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.deliverystatus', verbose_name='Estado del Despacho'),
            preserve_default=False,
        ),
    ]
