# Generated by Django 3.1.11 on 2021-08-07 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210807_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='employee_in_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_in_charge', to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_object_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
