# Generated by Django 3.1.11 on 2021-08-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210807_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billclientsubmission',
            name='product_requirements',
            field=models.TextField(),
        ),
    ]
