# Generated by Django 3.1.11 on 2021-08-17 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210816_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='billclientsubmission',
            name='handling_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billclientsubmission',
            name='has_been_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billclientsubmission',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
