# Generated by Django 3.1.11 on 2021-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210817_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
